### ISSUE TITLE
Possible errata in the book Fundamentals Of Computer Graphics 4th edition

### ISSUE THREAD

**Issue by velociraptor111** [alecjacobson/computer-graphics-csc418#3]
In chapter 12.3 and Fig 12.24 are the axes wrong ?

Shouldn't the ray on the left side be hitting t_ymin and t_ymax instead?
And on the right side it should be t_xmin and t_xmax . I think the author might have mixed up the axes.  Because if you see Fig 12.25 the way he defined the axis would also agree to the my understanding. 

<img width="748" alt="screen shot 2018-10-26 at 11 11 05 am" src="https://user-images.githubusercontent.com/19272937/47575341-e1278300-d90f-11e8-9066-c183c01e88b1.png">

**Comment by alecjacobson** [comment]
I think Marina stumbled upon this typo as well. I'm making a list of typos etc. to point out to the authors. Thanks for posting this.
